### ISSUE TITLE
stringLiteral, backtickLiteral broken

### ISSUE THREAD

**Issue by cseed** [broadinstitute/hail#493]
Example: ```$ hail ... exportvariants -o foo.btsv -c '"this is a \"'`

```
Exception in thread "main" java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:165)
	at org.broadinstitute.hail.expr.Parser$$anonfun$stringLiteral$2$$anonfun$apply$136.apply(Parser.scala:326)
	at org.broadinstitute.hail.expr.Parser$$anonfun$stringLiteral$2$$anonfun$apply$136.apply(Parser.scala:323)
	at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:136)
	...
```

**Comment by cseed** [comment]
Also add test case for unterminated string with nice error message (use `interceptFatal`).
