### ISSUE TITLE
VDS read fails when RDD is empty

### ISSUE THREAD

**Issue by tpoterba** [broadinstitute/hail#621]
```
hail importvcf src/test/resources/sample2.vcf filtervariants all write -o /tmp/out.vds read -i /tmp/out.vds count
hail: info: running: importvcf src/test/resources/sample2.vcf
hail: info: running: filtervariants all
hail: info: running: write -o /tmp/out.vds
hail: info: running: read -i /tmp/out.vds
Exception in thread "main" java.lang.AssertionError: assertion failed: No predefined schema found, and no Parquet data files or summary files found under file:/tmp/out.vds/rdd.parquet.
       	at scala.Predef$.assert(Predef.scala:179)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$MetadataCache.org$apache$spark$sql$execution$datasources$parquet$ParquetRelation$MetadataCache$$readSchema(ParquetRelation.scala:478)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$MetadataCache$$anonfun$13.apply(ParquetRelation.scala:404)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$MetadataCache$$anonfun$13.apply(ParquetRelation.scala:404)
       	at scala.Option.orElse(Option.scala:257)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$MetadataCache.refresh(ParquetRelation.scala:404)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation.org$apache$spark$sql$execution$datasources$parquet$ParquetRelation$$metadataCache$lzycompute(ParquetRelation.scala:145)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation.org$apache$spark$sql$execution$datasources$parquet$ParquetRelation$$metadataCache(ParquetRelation.scala:143)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$$anonfun$6.apply(ParquetRelation.scala:196)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation$$anonfun$6.apply(ParquetRelation.scala:196)
       	at scala.Option.getOrElse(Option.scala:120)
       	at org.apache.spark.sql.execution.datasources.parquet.ParquetRelation.dataSchema(ParquetRelation.scala:196)
       	at org.apache.spark.sql.sources.HadoopFsRelation.schema$lzycompute(interfaces.scala:561)
       	at org.apache.spark.sql.sources.HadoopFsRelation.schema(interfaces.scala:560)
       	at org.apache.spark.sql.execution.datasources.LogicalRelation.<init>(LogicalRelation.scala:31)
       	at org.apache.spark.sql.SQLContext.baseRelationToDataFrame(SQLContext.scala:389)
       	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:267)
       	at org.broadinstitute.hail.variant.VariantSampleMatrix$.read(VariantSampleMatrix.scala:132)
       	at org.broadinstitute.hail.driver.Read$.run(Read.scala:29)
       	at org.broadinstitute.hail.driver.Read$.run(Read.scala:6)
       	at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:238)
       	at org.broadinstitute.hail.driver.Main$.runCommand(Main.scala:86)
       	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:111)
       	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:111)
       	at org.broadinstitute.hail.Utils$.time(Utils.scala:1185)
       	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:110)
       	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:104)
       	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
       	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
       	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:108)
       	at org.broadinstitute.hail.driver.Main$.runCommands(Main.scala:104)
       	at org.broadinstitute.hail.driver.Main$.main(Main.scala:275)
       	at org.broadinstitute.hail.driver.Main.main(Main.scala)
```

**Comment by tpoterba** [comment]
Fixed in #688
