### ISSUE TITLE
Error message: hail: variantqc: caught exception: org.apache.spark.SparkException

### ISSUE THREAD

**Issue by seuchoi** [broadinstitute/hail#660]
While I was running the script shown below. I got the error message. I attach the log file. Do you know what cause the errors ? Thanks 

```
hail -l /medpop/afib/schoi/projects/TOPMed/Script/log/TopMed.Chr22.QC.vds.log \
importvcf file:///medpop/afib/schoi/projects/TOPMed/Data/BROAD/Link/Chr22/*.bgz splitmulti \
filtervariants expr -c 'v.contig == "X" || v.contig == "Y" || v.contig == "MT"' --remove \
filtersamples list -i file:///medpop/afib/schoi/projects/TOPMed/Result/TopMed_nodup.6998.sample.map --keep \
sampleqc -o file:///medpop/afib/schoi/projects/TOPMed/Result/SampleQC/chrom/TOPMed.PreQC.sampleqc.chr22.tsv \
variantqc -o file:///medpop/afib/schoi/projects/TOPMed/Result/VariantQC/chrom/TOPMed.PreQC.variantqc.chr22.tsv \
annotatevariants expr -c 'va.info.AC = va.info.AC[va.aIndex]' \
filtergenotypes -c '(g.ad[0] + g.ad[1]) / g.dp < 0.9 || (g.isHomRef && (g.ad[0] / g.dp < 0.9 || g.gq < 20)) || (g.isHet && (g.ad[1] / g.dp < 0.20 || g.pl[0] < 20)) || (g.isHomVar && (g.ad[1] / g.dp < 0.9 || g.pl[0] < 20)) || g.dp > 200' --remove \
variantqc -o file:///medpop/afib/schoi/projects/TOPMed/Result/VariantQC/chrom/TOPMed.QCstep1.variantqc.Chr22.tsv \
annotatevariants intervals -r va.isLCF -i file:///medpop/afib/schoi/projects/TOPMed/Data/LCR/LCR.interval_list \
annotatevariants expr -c 'va.AC1 = va.qc.AC,
va.good = ((va.info.QD > 3 && v.altAllele.isIndel) || (va.info.QD > 2 && v.altAllele.isSNP)) && (va.qc.callRate > 0.95)' \
annotateglobal expr -c 'global.badVQSLOD = variants.count(va.pass),
global.badQD = variants.count((va.info.QD <= 3 && v.altAllele.isIndel) || (va.info.QD <= 2 && v.altAllele.isSNP)),
global.badCallRate = variants.count(va.qc.callRate <= 0.95),
global.nIndel_1 = variants.count(v.altAllele.isIndel && va.AC1 > 0),
global.nSNP_1 = variants.count(v.altAllele.isSNP && va.AC1 > 0),
global.nIndel_2 = variants.count(v.altAllele.isIndel && va.AC1 > 0 && va.pass),
global.nSNP_2 = variants.count(v.altAllele.isSNP && va.AC1 > 0 && va.pass),
global.nIndel_3 = variants.count(v.altAllele.isIndel && va.AC1 > 0 && va.pass && !va.isLCF),
global.nSNP_3 = variants.count(v.altAllele.isSNP && va.AC1 > 0 && va.pass && !va.isLCF),
global.nIndel_4 = variants.count(v.altAllele.isIndel && va.AC1 > 0 && va.pass && !va.isLCF && va.qc.callRate > 0.80),
global.nSNP_4 = variants.count(v.altAllele.isSNP && va.AC1 > 0 && va.pass && !va.isLCF && va.qc.callRate > 0.80),
global.nIndel_5 = variants.count(v.altAllele.isIndel && va.AC1 > 0 && va.pass && !va.isLCF && va.good),
global.nSNP_5 = variants.count(v.altAllele.isSNP && va.AC1 > 0 && va.pass && !va.isLCF && va.good)' \
showglobals -o file:///medpop/afib/schoi/projects/TOPMed/Result/Global/chrom/TOPMed_showglobalsQC.chr22.txt \
filtervariants expr -c 'va.AC1 > 0 && va.pass && !va.isLCF && va.good' --keep \
sampleqc -o file:///medpop/afib/schoi/projects/TOPMed/Result/SampleQC/chrom/TOPMed.QCstep2.sampleqc.chr22.tsv \
variantqc -o file:///medpop/afib/schoi/projects/TOPMed/Result/VariantQC/chrom/TOPMed.QCstep2.variantqc.chr22.tsv \
exportvariants -c 'Chrom=v.contig,Pos=v.start,Ref=v.ref,Alt=v.alt, rsID = va.rsid,PASS = va.pass, MISSINGNESS = 1 - va.qc.callRate,QD = va.info.QD, InbreedingCoeff = va.info.InbreedingCoeff, VQSLOD = va.info.VQSLOD,MAC=va.qc.AC,MAF=va.qc.AF' -o file:///medpop/afib/schoi/projects/TOPMed/Result/VariantQC/chrom/TOPMed.QCstep2.variantqcv2.chr22.tsv \
write -o TOPMed.6998.chr22.vds
```

[TopMed.Chr22.QC.vds.log.txt](https://github.com/broadinstitute/hail/files/432676/TopMed.Chr22.QC.vds.log.txt)

**Comment by tpoterba** [comment]
```
2016-08-22 19:18:40 WARN  TaskSetManager:70 - Lost task 1.18 in stage 3.0 (TID 5385, dataflow05.broadinstitute.org): java.lang.ClassCastException: java.lang.Integer cannot be cast to scala.collection.IndexedSeq
        at org.broadinstitute.hail.expr.IndexOp$$anonfun$eval$217.apply(AST.scala:1780)
        at org.broadinstitute.hail.expr.AST$$anonfun$evalCompose$2.apply(AST.scala:128)
        at org.broadinstitute.hail.expr.Parser$$anonfun$5$$anonfun$apply$7.apply(Parser.scala:168)
        at org.broadinstitute.hail.expr.Parser$$anonfun$5$$anonfun$apply$7.apply(Parser.scala:168)
        at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2$$anonfun$apply$2.apply(AnnotateVariantsExpr.scala:71)
        at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2$$anonfun$apply$2.apply(AnnotateVariantsExpr.scala:70)
        at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
        at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
        at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:108)
        at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2.apply(AnnotateVariantsExpr.scala:70)
        at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2.apply(AnnotateVariantsExpr.scala:64)
        at org.broadinstitute.hail.variant.VariantSampleMatrix$$anonfun$mapAnnotations$1.apply(VariantSampleMatrix.scala:399)
        at org.broadinstitute.hail.variant.VariantSampleMatrix$$anonfun$mapAnnotations$1.apply(VariantSampleMatrix.scala:399)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:285)
        at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:171)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by tpoterba** [comment]
running on version 65bed04

**Comment by cseed** [comment]
I can reproduce the error in the current master with:

```
./build/install/hail/bin/hail importvcf ~/sample2.vcf splitmulti annotatevariants expr -c 'va.info.AC = va.info.AC[va.aIndex]' count
```

**Comment by seuchoi** [comment]
Can I use `annotatevariants expr -c 'va.info.AC = va.info.AC[va.aIndex]'` in dataflow ?

**Comment by seuchoi** [comment]
This still causes error messages. `hail -l /mnt/lustre/schoi/projects/TOPMed/BROAD/Chr22/TopMed.Chr${num}.QC.vds.test.log importvcf file:///mnt/lustre/schoi/projects/TOPMed/BROAD/Chr${num}/TopMed_8k.853.vcf.bgz splitmulti annotatevariants expr -c 'va.info.AC = va.info.AC[va.aIndex]' count`

`2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@log_env@716: Client environment:host.name=nid00014
2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@log_env@724: Client environment:os.arch=2.6.32-431.el6_1.0000.9051-cray_ari_athena_c_cos
2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Thu Jan 28 18:37:39 UTC 2016
2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@log_env@733: Client environment:user.name=schoi
2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@log_env@741: Client environment:user.home=/home/users/schoi
2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@log_env@753: Client environment:user.dir=/mnt/lustre/schoi/projects/TOPMed/BROAD/Chr22
2016-08-24 16:42:27,052:8532(0x7fef97fff700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=192.168.0.1:2181,192.168.0.9:2181,192.168.0.17:2181 sessionTimeout=10000 watcher=0x3b9c8c00a0 sessionId=0 sessionPasswd=<null> context=0x7fed6c000960 flags=0
I0824 16:42:27.052752  8752 sched.cpp:164] Version: 0.25.0
2016-08-24 16:42:27,053:8532(0x7fef76bfd700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.0.9:2181]
2016-08-24 16:42:27,070:8532(0x7fef76bfd700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.0.9:2181], sessionId=0x255cb9ea22102ec, negotiated timeout=10000
I0824 16:42:27.070502  8726 group.cpp:331] Group process (group(1)@192.168.0.15:12239) connected to ZooKeeper
I0824 16:42:27.070544  8726 group.cpp:805] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0824 16:42:27.070554  8726 group.cpp:403] Trying to create path '/mesos' in ZooKeeper
I0824 16:42:27.071593  8705 detector.cpp:156] Detected a new leader: (id='66')
I0824 16:42:27.071702  8746 group.cpp:674] Trying to get '/mesos/json.info_0000000066' in ZooKeeper
I0824 16:42:27.072525  8706 detector.cpp:481] A new leading master (UPID=master@192.168.0.9:5050) is detected
I0824 16:42:27.072593  8736 sched.cpp:262] New master detected at master@192.168.0.9:5050
I0824 16:42:27.072742  8736 sched.cpp:272] No credentials provided. Attempting to register without authentication
I0824 16:42:27.074246  8746 sched.cpp:641] Framework registered with 0233fcf9-88ce-407f-8ed5-b015adf9b59c-1932
hail: info: running: importvcf file:///mnt/lustre/schoi/projects/TOPMed/BROAD/Chr22/TopMed_8k.853.vcf.bgz
[Stage 0:=====================================================>   (53 + 3) / 56]hail: info: Ordering unsorted dataset with network shuffle
hail: info: running: splitmulti
hail: info: running: annotatevariants expr -c 'va.info.AC = va.info.AC[va.aIndex]'
hail: info: running: count
[Stage 3:>                                                        (0 + 56) / 56]hail: count: caught exception: org.apache.spark.SparkException: Job aborted due to stage failure: Task 50 in stage 3.0 failed 4 times, most recent failure: Lost task 50.3 in stage 3.0 (TID 296, nid00004.urika.com): java.lang.ClassCastException: java.lang.Integer cannot be cast to scala.collection.IndexedSeq
	at org.broadinstitute.hail.expr.IndexOp$$anonfun$eval$224.apply(AST.scala:1894)
	at org.broadinstitute.hail.expr.AST$$anonfun$evalCompose$2.apply(AST.scala:129)
	at org.broadinstitute.hail.expr.Parser$$anonfun$5$$anonfun$apply$7.apply(Parser.scala:168)
	at org.broadinstitute.hail.expr.Parser$$anonfun$5$$anonfun$apply$7.apply(Parser.scala:168)
	at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2$$anonfun$apply$2.apply(AnnotateVariantsExpr.scala:71)
	at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2$$anonfun$apply$2.apply(AnnotateVariantsExpr.scala:70)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:108)
	at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2.apply(AnnotateVariantsExpr.scala:70)
	at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2.apply(AnnotateVariantsExpr.scala:64)
	at org.broadinstitute.hail.variant.VariantSampleMatrix$$anonfun$25.apply(VariantSampleMatrix.scala:423)
	at org.broadinstitute.hail.variant.VariantSampleMatrix$$anonfun$25.apply(VariantSampleMatrix.scala:423)
	at org.broadinstitute.hail.RichPairRDD$$anonfun$mapValuesWithKey$extension$1$$anonfun$apply$5.apply(Utils.scala:459)
	at org.broadinstitute.hail.RichPairRDD$$anonfun$mapValuesWithKey$extension$1$$anonfun$apply$5.apply(Utils.scala:459)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1555)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1125)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1125)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1283)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1271)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1270)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1270)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:697)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1496)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1458)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1447)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:567)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1824)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1837)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1850)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1921)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1125)
	at org.broadinstitute.hail.driver.Count$.run(Count.scala:37)
	at org.broadinstitute.hail.driver.Count$.run(Count.scala:9)
	at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:239)
	at org.broadinstitute.hail.driver.Main$.runCommand(Main.scala:120)
	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:144)
	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:144)
	at org.broadinstitute.hail.Utils$.time(Utils.scala:1282)
	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:143)
	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:137)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:108)
	at org.broadinstitute.hail.driver.Main$.runCommands(Main.scala:137)
	at org.broadinstitute.hail.driver.Main$.main(Main.scala:286)
	at org.broadinstitute.hail.driver.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)java.lang.ClassCastException: java.lang.Integer cannot be cast to scala.collection.IndexedSeq
	at org.broadinstitute.hail.expr.IndexOp$$anonfun$eval$224.apply(AST.scala:1894)
	at org.broadinstitute.hail.expr.AST$$anonfun$evalCompose$2.apply(AST.scala:129)
	at org.broadinstitute.hail.expr.Parser$$anonfun$5$$anonfun$apply$7.apply(Parser.scala:168)
	at org.broadinstitute.hail.expr.Parser$$anonfun$5$$anonfun$apply$7.apply(Parser.scala:168)
	at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2$$anonfun$apply$2.apply(AnnotateVariantsExpr.scala:71)
	at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2$$anonfun$apply$2.apply(AnnotateVariantsExpr.scala:70)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:108)
	at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2.apply(AnnotateVariantsExpr.scala:70)
	at org.broadinstitute.hail.driver.AnnotateVariantsExpr$$anonfun$2.apply(AnnotateVariantsExpr.scala:64)
	at org.broadinstitute.hail.variant.VariantSampleMatrix$$anonfun$25.apply(VariantSampleMatrix.scala:423)
	at org.broadinstitute.hail.variant.VariantSampleMatrix$$anonfun$25.apply(VariantSampleMatrix.scala:423)
	at org.broadinstitute.hail.RichPairRDD$$anonfun$mapValuesWithKey$extension$1$$anonfun$apply$5.apply(Utils.scala:459)
	at org.broadinstitute.hail.RichPairRDD$$anonfun$mapValuesWithKey$extension$1$$anonfun$apply$5.apply(Utils.scala:459)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1555)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1125)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1125)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1850)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
I0824 16:44:07.061986  9121 sched.cpp:1771] Asked to stop the driver
I0824 16:44:07.062144  8743 sched.cpp:1040] Stopping framework '0233fcf9-88ce-407f-8ed5-b015adf9b59c-1932'`
