### ISSUE TITLE
Error for importvcf 

### ISSUE THREAD

**Issue by seuchoi** [broadinstitute/hail#669]
I got the error message while importing VCFs in dataflow01

`hail -l /medpop/afib/schoi/projects/TOPMed/Script/log/TopMed.Chr22.QC.vds.test.log \
 importvcf file:///medpop/afib/schoi/projects/TOPMed/Data/BROAD/Link/Chr22/TopMed_8k.853.vcf.bgz \ splitmulti \
write -o TOPMed.6998.chr22.vds`

`[Stage 0:====================================================>    (52 + 4) / 56]hail: info: Ordering unsorted dataset with network shuffle
hail: importvcf: caught exception: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:106)
	at org.apache.spark.rdd.OrderedRDD$$anonfun$calculateKeyRanges$1.apply(OrderedRDD.scala:143)
	at org.apache.spark.rdd.OrderedRDD$$anonfun$calculateKeyRanges$1.apply(OrderedRDD.scala:142)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.apache.spark.rdd.OrderedRDD$.calculateKeyRanges(OrderedRDD.scala:142)
	at org.apache.spark.rdd.OrderedRDD$.apply(OrderedRDD.scala:117)
	at org.broadinstitute.hail.RichPairRDD$.toOrderedRDD$extension(Utils.scala:482)
	at org.broadinstitute.hail.io.vcf.LoadVCF$.apply(LoadVCF.scala:267)
	at org.broadinstitute.hail.driver.ImportVCF$.run(ImportVCF.scala:85)
	at org.broadinstitute.hail.driver.ImportVCF$.run(ImportVCF.scala:31)
	at org.broadinstitute.hail.driver.Command.runCommand(Command.scala:239)
	at org.broadinstitute.hail.driver.Main$.runCommand(Main.scala:120)
	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:144)
	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1$$anonfun$1.apply(Main.scala:144)
	at org.broadinstitute.hail.Utils$.time(Utils.scala:1282)
	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:143)
	at org.broadinstitute.hail.driver.Main$$anonfun$runCommands$1.apply(Main.scala:137)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:108)
	at org.broadinstitute.hail.driver.Main$.runCommands(Main.scala:137)
	at org.broadinstitute.hail.driver.Main$.main(Main.scala:286)
	at org.broadinstitute.hail.driver.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)`

**Comment by tpoterba** [comment]
This is an issue with deploying on spark 1.6.0.  Subsumed by #667
